[package]
name = "Ampersand"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monster_chess = "0.0.24"
monster_ugi = "0.0.19"
rand = "0.8.5"